In [1]:
import pandas as pd
import numpy as np

data_2008 = pd.read_csv('all_alpha_08.csv')
data_2018 = pd.read_csv('all_alpha_18.csv')

# ASSESSING DATA

    1.number of samples in each dataset
    2.number of columns in each dataset
    3.duplicate rows in each dataset
    4.datatypes of columns
    5.features with missing values
    6.number of non-null unique values for features in each dataset
    7.what those unique values are and counts for each

### For Data in 2008

In [2]:
data_2008.head()

,Model,Displ,Cyl,Trans,Drive,Fuel,Sales Area,Stnd,Underhood ID,Veh Class,Air Pollution Score,FE Calc Appr,City MPG,Hwy MPG,Cmb MPG,Unadj Cmb MPG,Greenhouse Gas Score,SmartWay
0,ACURA MDX,3.7,(6 cyl),Auto-S5,4WD,Gasoline,CA,U2,8HNXT03.7PKR,SUV,7,Drv,15,20,17,22.0527,4,no
1,ACURA MDX,3.7,(6 cyl),Auto-S5,4WD,Gasoline,FA,B5,8HNXT03.7PKR,SUV,6,Drv,15,20,17,22.0527,4,no
2,ACURA RDX,2.3,(4 cyl),Auto-S5,4WD,Gasoline,CA,U2,8HNXT02.3DKR,SUV,7,Drv,17,22,19,24.1745,5,no
3,ACURA RDX,2.3,(4 cyl),Auto-S5,4WD,Gasoline,FA,B5,8HNXT02.3DKR,SUV,6,Drv,17,22,19,24.1745,5,no
4,ACURA RL,3.5,(6 cyl),Auto-S5,4WD,Gasoline,CA,U2,8HNXV03.5HKR,midsize car,7,Drv,16,24,19,24.5629,5,no

In [3]:
# to extract basic information of the dataset
data_2008.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2404 entries, 0 to 2403
Data columns (total 18 columns):
Model                   2404 non-null object
Displ                   2404 non-null float64
Cyl                     2205 non-null object
Trans                   2205 non-null object
Drive                   2311 non-null object
Fuel                    2404 non-null object
Sales Area              2404 non-null object
Stnd                    2404 non-null object
Underhood ID            2404 non-null object
Veh Class               2404 non-null object
Air Pollution Score     2404 non-null object
FE Calc Appr            2205 non-null object
City MPG                2205 non-null object
Hwy MPG                 2205 non-null object
Cmb MPG                 2205 non-null object
Unadj Cmb MPG           2205 non-null float64
Greenhouse Gas Score    2205 non-null object
SmartWay                2404 non-null object
dtypes: float64(2), object(16)
memory usage: 338.1+ KB

In [4]:
# to check the number of duplicate values in the table
data_2008.duplicated().sum()

25

In [5]:
# to check the null values in the table
data_2008.isnull().sum()

Model                     0
Displ                     0
Cyl                     199
Trans                   199
Drive                    93
Fuel                      0
Sales Area                0
Stnd                      0
Underhood ID              0
Veh Class                 0
Air Pollution Score       0
FE Calc Appr            199
City MPG                199
Hwy MPG                 199
Cmb MPG                 199
Unadj Cmb MPG           199
Greenhouse Gas Score    199
SmartWay                  0
dtype: int64

In [6]:
# to check the data types of the Column
data_2008.dtypes

Model                    object
Displ                   float64
Cyl                      object
Trans                    object
Drive                    object
Fuel                     object
Sales Area               object
Stnd                     object
Underhood ID             object
Veh Class                object
Air Pollution Score      object
FE Calc Appr             object
City MPG                 object
Hwy MPG                  object
Cmb MPG                  object
Unadj Cmb MPG           float64
Greenhouse Gas Score     object
SmartWay                 object
dtype: object

In [7]:
# to check the unique values present in the data 
data_2008.nunique()

Model                   436
Displ                    47
Cyl                       8
Trans                    14
Drive                     2
Fuel                      5
Sales Area                3
Stnd                     12
Underhood ID            343
Veh Class                 9
Air Pollution Score      13
FE Calc Appr              2
City MPG                 39
Hwy MPG                  43
Cmb MPG                  38
Unadj Cmb MPG           721
Greenhouse Gas Score     20
SmartWay                  2
dtype: int64

### For data in 2018

In [8]:
# to extract the basic information of the dataset
data_2018.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1611 entries, 0 to 1610
Data columns (total 18 columns):
Model                   1611 non-null object
Displ                   1609 non-null float64
Cyl                     1609 non-null float64
Trans                   1611 non-null object
Drive                   1611 non-null object
Fuel                    1611 non-null object
Cert Region             1611 non-null object
Stnd                    1611 non-null object
Stnd Description        1611 non-null object
Underhood ID            1611 non-null object
Veh Class               1611 non-null object
Air Pollution Score     1611 non-null int64
City MPG                1611 non-null object
Hwy MPG                 1611 non-null object
Cmb MPG                 1611 non-null object
Greenhouse Gas Score    1611 non-null int64
SmartWay                1611 non-null object
Comb CO2                1611 non-null object
dtypes: float64(2), int64(2), object(14)
memory usage: 226.6+ KB

In [9]:
# to check the number of duplicate values in the table
data_2018.duplicated().sum()

0

In [10]:
# to check the number of null values in the table
data_2018.isnull().sum()

Model                   0
Displ                   2
Cyl                     2
Trans                   0
Drive                   0
Fuel                    0
Cert Region             0
Stnd                    0
Stnd Description        0
Underhood ID            0
Veh Class               0
Air Pollution Score     0
City MPG                0
Hwy MPG                 0
Cmb MPG                 0
Greenhouse Gas Score    0
SmartWay                0
Comb CO2                0
dtype: int64

In [11]:
# to check the data type of the columns
data_2018.dtypes

Model                    object
Displ                   float64
Cyl                     float64
Trans                    object
Drive                    object
Fuel                     object
Cert Region              object
Stnd                     object
Stnd Description         object
Underhood ID             object
Veh Class                object
Air Pollution Score       int64
City MPG                 object
Hwy MPG                  object
Cmb MPG                  object
Greenhouse Gas Score      int64
SmartWay                 object
Comb CO2                 object
dtype: object

In [12]:
# to check the unique values present in the table
data_2018.nunique()

Model                   367
Displ                    36
Cyl                       7
Trans                    26
Drive                     2
Fuel                      5
Cert Region               2
Stnd                     19
Stnd Description         19
Underhood ID            230
Veh Class                 9
Air Pollution Score       6
City MPG                 58
Hwy MPG                  62
Cmb MPG                  57
Greenhouse Gas Score     10
SmartWay                  3
Comb CO2                299
dtype: int64

# Cleaning of Data

    1. Drop extraneous columns : Drop features that aren't consistent (not present in both datasets) or aren't relevant to our questions. Use pandas' drop function.
    
    2. Rename Columns :

In [13]:
# dropping features from data_2008

data_2008 = data_2008.drop(columns = ['Stnd','Underhood ID', 'FE Calc Appr', 'Unadj Cmb MPG'])
data_2008.head(1)

,Model,Displ,Cyl,Trans,Drive,Fuel,Sales Area,Veh Class,Air Pollution Score,City MPG,Hwy MPG,Cmb MPG,Greenhouse Gas Score,SmartWay
0,ACURA MDX,3.7,(6 cyl),Auto-S5,4WD,Gasoline,CA,SUV,7,15,20,17,4,no

In [14]:
# dropping data from data_2018

data_2018 = data_2018.drop(columns = ['Stnd', 'Stnd Description', 'Underhood ID', 'Comb CO2'])
data_2018.head(1)

,Model,Displ,Cyl,Trans,Drive,Fuel,Cert Region,Veh Class,Air Pollution Score,City MPG,Hwy MPG,Cmb MPG,Greenhouse Gas Score,SmartWay
0,ACURA RDX,3.5,6.0,SemiAuto-6,2WD,Gasoline,FA,small SUV,3,20,28,23,5,No

In [15]:
# renaming 'Sale Area' column to 'Cert Region'

data_2008 = data_2008.rename(columns = {'Sales Area' : 'Cert Region'})
data_2008

,Model,Displ,Cyl,Trans,Drive,Fuel,Cert Region,Veh Class,Air Pollution Score,City MPG,Hwy MPG,Cmb MPG,Greenhouse Gas Score,SmartWay
0,ACURA MDX,3.7,(6 cyl),Auto-S5,4WD,Gasoline,CA,SUV,7,15,20,17,4,no
1,ACURA MDX,3.7,(6 cyl),Auto-S5,4WD,Gasoline,FA,SUV,6,15,20,17,4,no
2,ACURA RDX,2.3,(4 cyl),Auto-S5,4WD,Gasoline,CA,SUV,7,17,22,19,5,no
3,ACURA RDX,2.3,(4 cyl),Auto-S5,4WD,Gasoline,FA,SUV,6,17,22,19,5,no
4,ACURA RL,3.5,(6 cyl),Auto-S5,4WD,Gasoline,CA,midsize car,7,16,24,19,5,no
5,ACURA RL,3.5,(6 cyl),Auto-S5,4WD,Gasoline,FA,midsize car,6,16,24,19,5,no
6,ACURA TL,3.2,(6 cyl),Auto-S5,2WD,Gasoline,CA,midsize car,7,18,26,21,6,yes
7,ACURA TL,3.5,(6 cyl),Auto-S5,2WD,Gasoline,CA,midsize car,7,17,26,20,6,yes
8,ACURA TL,3.5,(6 cyl),Man-6,2WD,Gasoline,CA,midsize car,7,18,27,21,6,yes
9,ACURA TL,3.2,(6 cyl),Auto-S5,2WD,Gasoline,FA,midsize car,6,18,26,21,6,no
10,ACURA TL,3.5,(6 cyl),Auto-S5,2WD,Gasoline,FA,midsize car,6,17,26,20,6,no
11,ACURA TL,3.5,(6 cyl),Man-6,2WD,Gasoline,FA,midsize car,6,18,27,21,6,no
12,ACURA TSX,2.4,(4 cyl),Man-6,2WD,Gasoline,FA,small car,6,19,28,22,6,no
13,ACURA TSX,2.4,(4 cyl),Auto-S5,2WD,Gasoline,FA,small car,6,20,28,23,7,yes
14,ACURA TSX,2.4,(4 cyl),Man-6,2WD,Gasoline,CA,small car,6,19,28,22,6,no
15,ACURA TSX,2.4,(4 cyl),Auto-S5,2WD,Gasoline,CA,small car,6,20,28,23,7,yes
16,ASTON MARTIN DB9,5.9,(12 cyl),Man-6,2WD,Gasoline,FA,small car,6,10,16,12,0,no
17,ASTON MARTIN DB9,5.9,(12 cyl),Auto-S6,2WD,Gasoline,FA,small car,6,11,18,13,1,no
18,ASTON MARTIN DB9,5.9,(12 cyl),Man-6,2WD,Gasoline,CA,small car,6,10,16,12,0,no
19,ASTON MARTIN DB9,5.9,(12 cyl),Auto-S6,2WD,Gasoline,CA,small car,6,11,18,13,1,no
20,ASTON MARTIN DB9 Volante,5.9,(12 cyl),Man-6,2WD,Gasoline,FA,small car,6,10,16,12,0,no
21,ASTON MARTIN DB9 Volante,5.9,(12 cyl),Auto-S6,2WD,Gasoline,FA,small car,6,11,17,13,1,no
22,ASTON MARTIN DB9 Volante,5.9,(12 cyl),Man-6,2WD,Gasoline,CA,small car,6,10,16,12,0,no
23,ASTON MARTIN DB9 Volante,5.9,(12 cyl),Auto-S6,2WD,Gasoline,CA,small car,6,11,17,13,1,no
24,ASTON MARTIN V8 Vantage,4.3,(8 cyl),Man-6,2WD,Gasoline,FA,small car,6,12,19,15,3,no
25,ASTON MARTIN V8 Vantage,4.3,(8 cyl),Auto-S6,2WD,Gasoline,FA,small car,6,13,20,15,3,no
26,ASTON MARTIN V8 Vantage,4.3,(8 cyl),Man-6,2WD,Gasoline,CA,small car,6,12,19,15,3,no
27,ASTON MARTIN V8 Vantage,4.3,(8 cyl),Auto-S6,2WD,Gasoline,CA,small car,6,13,20,15,3,no
28,AUDI A3,2.0,(4 cyl),Man-6,2WD,Gasoline,CA,station wagon,7,21,29,24,7,yes
29,AUDI A3,2.0,(4 cyl),Auto-S6,2WD,Gasoline,CA,station wagon,7,22,29,25,7,yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2374,VOLVO S80,3.2,(6 cyl),Auto-S6,2WD,Gasoline,CA,midsize car,7,16,24,19,5,no
2375,VOLVO S80,3.2,(6 cyl),Auto-S6,4WD,Gasoline,CA,midsize car,7,16,24,19,5,no
2376,VOLVO S80,4.4,(8 cyl),Auto-S6,4WD,Gasoline,CA,midsize car,7,15,23,18,5,no
2377,VOLVO S80,3.0,(6 cyl),Auto-S6,4WD,Gasoline,FA,midsize car,6,15,23,18,5,no
2378,VOLVO S80,3.2,(6 cyl),Auto-S6,2WD,Gasoline,FA,midsize car,6,16,24,19,5,no
2379,VOLVO S80,3.2,(6 cyl),Auto-S6,4WD,Gasoline,FA,midsize car,6,16,24,19,5,no
2380,VOLVO S80,4.4,(8 cyl),Auto-S6,4WD,Gasoline,FA,midsize car,6,15,23,18,5,no
2381,VOLVO V50,2.4,(5 cyl),Auto-S5,2WD,Gasoline,CA,station wagon,9.5,20,28,23,7,yes
2382,VOLVO V50,2.4,(5 cyl),Auto-S5,2WD,Gasoline,CA,station wagon,7,20,28,23,7,yes
2383,VOLVO V50,2.4,(5 cyl),Man-5,2WD,Gasoline,CA,station wagon,7,20,28,23,7,yes
2384,VOLVO V50,2.5,(5 cyl),Man-6,4WD,Gasoline,CA,station wagon,7,17,25,20,6,yes
2385,VOLVO V50,2.5,(5 cyl),Auto-S5,4WD,Gasoline,CA,station wagon,7,18,26,21,6,yes
2386,VOLVO V50,2.5,(5 cyl),Auto-S5,2WD,Gasoline,CA,station wagon,7,19,27,22,6,yes
2387,VOLVO V50,2.5,(5 cyl),Man-6,2WD,Gasoline,CA,station wagon,7,19,28,23,7,yes
2388,VOLVO V50,2.4,(5 cyl),Auto-S5,2WD,Gasoline,FA,station wagon,6,20,28,23,7,yes
2389,VOLVO V50,2.4,(5 cyl),Man-5,2WD,Gasoline,FA,station wagon,6,20,28,23,7,yes
2390,VOLVO V50,2.5,(5 cyl),Man-6,4WD,Gasoline,FA,station wagon,6,17,25,20,6,no
2391,VOLVO V50,2.5,(5 cyl),Auto-S5,4WD,Gasoline,FA,station wagon,6,18,26,21,6,no
2392,VOLVO V50,2.5,(5 cyl),Auto-S5,2WD,Gasoline,FA,station wagon,6,19,27,22,6,no
2393,VOLVO V50,2.5,(5 cyl),Man-6,2WD,Gasoline,FA,station wagon,6,19,28,23,7,yes
2394,VOLVO V70,3.2,(6 cyl),Auto-S6,2WD,Gasoline,CA,station wagon,7,16,24,19,5,no
2395,VOLVO V70,3.2,(6 cyl),Auto-S6,2WD,Gasoline,FA,station wagon,6,16,24,19,5,no
2396,VOLVO XC 70,3.2,(6 cyl),Auto-S6,4WD,Gasoline,CA,SUV,7,15,22,17,4,no
2397,VOLVO XC 70,3.2,(6 cyl),Auto-S6,4WD,Gasoline,FA,SUV,6,15,22,17,4,no
2398,VOLVO XC 90,3.2,(6 cyl),Auto-S6,2WD,Gasoline,CA,SUV,7,14,20,16,4,no
2399,VOLVO XC 90,3.2,(6 cyl),Auto-S6,4WD,Gasoline,CA,SUV,7,14,20,16,4,no
2400,VOLVO XC 90,4.4,(8 cyl),Auto-S6,4WD,Gasoline,CA,SUV,7,13,19,15,3,no
2401,VOLVO XC 90,3.2,(6 cyl),Auto-S6,2WD,Gasoline,FA,SUV,6,14,20,16,4,no
2402,VOLVO XC 90,3.2,(6 cyl),Auto-S6,4WD,Gasoline,FA,SUV,6,14,20,16,4,no
2403,VOLVO XC 90,4.4,(8 cyl),Auto-S6,4WD,Gasoline,FA,SUV,6,13,19,15,3,no

In [16]:
# replace spaces with underscores and lowercase labels for 2008 dataset
data_2008.rename(columns = lambda x : x.strip().lower().replace(' ','_'), inplace = True)

# confirm changes
data_2008.head(1)

,model,displ,cyl,trans,drive,fuel,cert_region,veh_class,air_pollution_score,city_mpg,hwy_mpg,cmb_mpg,greenhouse_gas_score,smartway
0,ACURA MDX,3.7,(6 cyl),Auto-S5,4WD,Gasoline,CA,SUV,7,15,20,17,4,no

In [17]:
# replace spaces with underscores and lowercase labels for 2018 dataset
data_2018.rename(columns = lambda x: x.strip().lower().replace(' ','_'), inplace = True)

# confirm changes
data_2018.head(1)

,model,displ,cyl,trans,drive,fuel,cert_region,veh_class,air_pollution_score,city_mpg,hwy_mpg,cmb_mpg,greenhouse_gas_score,smartway
0,ACURA RDX,3.5,6.0,SemiAuto-6,2WD,Gasoline,FA,small SUV,3,20,28,23,5,No

In [18]:
# confirm column labels for 2008 and 2018 datasets are identical
(data_2008.columns == data_2018.columns).all()

True

In [20]:
# saving changes to new repositary 
data_2008.to_csv('data_2008_v1.csv')
data_2018.to_csv('data_2018_v1.csv')